# ===============================
# Server Configuration
# ===============================
server:
  port: 8080
  servlet:
    context-path: /

# ===============================
# Application Configuration
# ===============================
spring:
  application:
    name: speech-therapy-backend
  
  # ===============================
  # Database Configuration
  # ===============================
  datasource:
    url: jdbc:mysql://localhost:3306/speech_therapy?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: Visithran@mysql#123
    driver-class-name: com.mysql.cj.jdbc.Driver
    
    # ===============================
    # Connection Pool (HikariCP)
    # ===============================
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
  
  # ===============================
  # JPA / Hibernate Configuration
  # ===============================
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        use_sql_comments: true
  
  # ===============================
  # Multipart Configuration
  # ===============================
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  
  # ===============================
  # Jackson Configuration
  # ===============================
  jackson:
    serialization:
      indent_output: true
    deserialization:
      fail_on_unknown_properties: false
  
  # ===============================
  # Additional Settings
  # ===============================
  main:
    allow-bean-definition-overriding: true
  
  profiles:
    active: dev

# ===============================
# Logging Configuration
# ===============================
logging:
  level:
    com.speechtherapy: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.security: DEBUG

# ===============================
# Management Endpoints
# ===============================
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env
  endpoint:
    health:
      show-details: always
      show-components: always